name: Check CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Spotless Check
        run: ./gradlew spotlessCheck --stacktrace --no-daemon --no-parallel

  build:
    name: Gradle check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Lint
        run: ./gradlew lint --stacktrace --no-daemon --no-parallel

      - name: Assemble
        run: ./gradlew assemble --stacktrace --no-daemon --no-parallel

      - name: Build
        run: ./gradlew build --stacktrace --no-daemon --no-parallel