name: deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  publish_maven:
    name: Publish Maven
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_KEY_ARMOR" | base64 --decode > ./release.asc
          gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc
        env:
          GPG_KEY_ARMOR: ${{ secrets.GPG_KEY_ARMOR }}

      - name: Configure Gradle Properties
        run: |
          sed -i -e "s,nexusUsername=,nexusUsername=$NEXUS_USERNAME,g" gradle.properties
          sed -i -e "s,nexusPassword=,nexusPassword=$NEXUS_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
          sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties
        env:
          GPG_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Publish to Sonatype
        run: ./gradlew :publish

      - name: Close and release on Sonatype
        uses: monkeyWie/maven-nexus-release@v1.0.0
        with:
          maven-repo-server-username: ${{ secrets.NEXUS_USERNAME }}
          maven-repo-server-password: ${{ secrets.NEXUS_PASSWORD }}