name: deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  publish_maven:
    name: Publish Maven
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Apply Signing
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./.github/apply_signing.sh

      - name: Publish to Sonatype
        run: ./gradlew :image-loader:publish --stacktrace --no-daemon --no-parallel

#      - name: Close and release on Sonatype
#        uses: monkeyWie/maven-nexus-release@v1.0.0
#        with:
#          maven-repo-server-username: ${{ secrets.NEXUS_USERNAME }}
#          maven-repo-server-password: ${{ secrets.NEXUS_PASSWORD }}