name: Merge Bot

on:
  workflow_run:
    workflows: [Label bot, Release CI]
    types:
      - completed

concurrency:
  group: merge-bot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: PR Merge Bot
        id: merge
        uses: Tlaster/auto-merger@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch release event
        if: ${{ steps.merge.outputs.merged == 'true' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          ready_label: ready_for_review
          approved_label: approved
          event-type: release-event