name: publish

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.event.pull_request.number }}-ci
  cancel-in-progress: true

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/configs/changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          toTag: "${{ steps.release_vars.outputs.version }}"

      - name: Echo Configuration Changelog
        env:
          CHANGELOG: ${{ steps.github_release.outputs.changelog }}
        run: echo "CHANGELOG"

#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          body: ${{ steps.github_release.outputs.changelog }}
